name: flutter_adaptive_cards_plus
description: A Flutter implementation of Adaptive Cards, updated for Flutter 3.35.2.
version: 1.0.0
homepage: https://github.com/HRCJ7/flutter_adaptive_cards_plus
repository: https://github.com/HRCJ7/flutter_adaptive_cards_plus
issue_tracker: https://github.com/HRCJ7/flutter_adaptive_cards_plus/issues
license: MIT
publish_to: "https://pub.dev"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ">=0.19.0 <0.21.0"
  provider: ^6.1.2
  flutter_markdown: ^0.7.3
  video_player: ^2.9.2
  chewie: ^1.7.5
  uuid: ^4.4.0
  tinycolor2: ^3.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  test_core: any

flutter:
# You can define package assets here if needed
# assets:
#   - assets/host_config.json
#
# Example for adding custom fonts:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf