name: flutter_adaptive_cards_plus
description: A Flutter implementation of Adaptive Cards.
version: 0.0.1
author: Norbert Kozsir <norbert@neohelden.com>
homepage: https://github.com/neohelden/Flutter-AdaptiveCards

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ">=0.19.0 <0.21.0"
  provider: ^6.1.2
  flutter_markdown: ^0.7.3
  video_player: ^2.9.2
  chewie: ^1.7.5
  uuid: ^4.4.0
  tinycolor2: ^3.0.1
  url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
  mockito: any
  test_core: any
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
